### ISSUE TITLE
Cannot access gated repo

### ISSUE THREAD

**Issue by yhd-ai** [Stability-AI/stable-fast-3d#11]
I got this error
Cannot access gated repo for url https://huggingface.co/stabilityai/stable-fast-3d/resolve/main/config.yaml.
Access to model stabilityai/stable-fast-3d is restricted. You must be authenticated to access it.

**Comment by MNeMoNiCuZ** [comment]
I've had the same error for this, and neither this solution, nor signing in with `huggingface-cli login` works for me.

I've done the environment setup twice to make sure I didn't miss anything, I got to this same result on both setups.


On HF the model is clearly accessible:
![image](https://github.com/user-attachments/assets/fa18651f-167f-45ab-8156-bf9ac0b56bb8)

![image](https://github.com/user-attachments/assets/5918f4df-9b41-4434-96b7-4d010831a337)

**Comment by SSJGabraham** [comment]
> You need HuggingFace account first, and then follow this tips:
> 
> 1. Gated model, fill in the form (name / email / company .. )
>    https://huggingface.co/spaces/stabilityai/stable-fast-3d
> 2. HuggingFace  >> Setting >> Access Tokens >> Create new token
>    https://huggingface.co/settings/tokens
> 3. pip install huggingface_hub
> 4. python -c "from huggingface_hub.hf_api import HfFolder; HfFolder.save_token('XXXXXXX')"
>    replace your self token
> 
> enjoy it😎

This worked for me. Much appreciated.

**Comment by FishGPT** [comment]
> I've had the same error for this, and neither this solution, nor signing in with `huggingface-cli login` works for me.
> 
> I've done the environment setup twice to make sure I didn't miss anything, I got to this same result on both setups.
> 
> On HF the model is clearly accessible: ![image](https://private-user-images.githubusercontent.com/60541708/354691531-fa18651f-167f-45ab-8156-bf9ac0b56bb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NzA0NDEsIm5iZiI6MTcyMjY3MDE0MSwicGF0aCI6Ii82MDU0MTcwOC8zNTQ2OTE1MzEtZmExODY1MWYtMTY3Zi00NWFiLTgxNTYtYmY5YWMwYjU2YmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDA3MjkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiOTE5ODlhMGEwNTg5YWQ0ODcwYTY5YTdkNzExNTQwOTg5MzZkNGIyNjQ5YTJhMWYyM2QyZWEzMTkyNmI5MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U6NEaxzhGkzjdUqIkkKOpAclXQSCaayTfEqTPrfGhpA)
> 
> ![image](https://private-user-images.githubusercontent.com/60541708/354691902-5918f4df-9b41-4434-96b7-4d010831a337.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NzA0NDEsIm5iZiI6MTcyMjY3MDE0MSwicGF0aCI6Ii82MDU0MTcwOC8zNTQ2OTE5MDItNTkxOGY0ZGYtOWI0MS00NDM0LTk2YjctNGQwMTA4MzFhMzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDA3MjkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMTQ5NTQxZGRiNWViMWQ3ZmZmYmM4YmJkZGRhMTAzNGU2ZGIzOWY4YWEzNzdkMWM0OTFhNjgzN2VkYjM5ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x2PBtcRC85io6ny7RHAQ0SHtDS1yYBSB9KkeJg5pC0c)

I think you can try create new token with Permission READ

1. huggingface-cli delete-cache
2. huggingface-cli logout
3. huggingface-cli login
4. huggingface-cli whoami
    Check your HuggingFace's name print on screen

**Comment by MNeMoNiCuZ** [comment]
> > You need HuggingFace account first, and then follow this tips:
> > 
> > 1. Gated model, fill in the form (name / email / company .. )
> >    https://huggingface.co/spaces/stabilityai/stable-fast-3d
> > 2. HuggingFace  >> Setting >> Access Tokens >> Create new token
> >    https://huggingface.co/settings/tokens
> > 3. pip install huggingface_hub
> > 4. python -c "from huggingface_hub.hf_api import HfFolder; HfFolder.save_token('XXXXXXX')"
> >    replace your self token
> > 
> > enjoy it😎
> 
> This worked for me. Much appreciated.

Thank you! Those steps solved it for me, with the caveat that I had to restart the CLI at some point to get it to refresh.
