### ISSUE TITLE
About quadrilateral remeshed object 's export

### ISSUE THREAD

**Issue by seongyeong2** [Stability-AI/stable-fast-3d#22]
Hello, I'm grateful to have come across such brilliant research.

I'm particularly interested in remeshing and mesh export using UV mapping. 
It's great that quadrilateral remeshing is possible with a Python package, 
but it seems the mesh is exported as triangles due to the texture mapping process.

Is there a way to remesh and export a textured mesh with quadrilateral faces?

Thank you.

**Comment by Banbury** [comment]
The Python script has an option for remeshing with quads. But depending on your model, you might be better off using a something like Houdini for remeshing.

**Comment by seongyeong2** [comment]
I am aware of and have been using the remeshing with quads, so thank you for that.

What I was referring to, though, is that even when I perform quadrilateral remeshing, the exported mesh gets converted to triangle faces. I’m curious if it’s possible to obtain a mesh composed entirely of quadrilateral faces even after export.

If I’ve missed something, please let me know. Thank you!

**Comment by Banbury** [comment]
Technically there are only triangles. But Blender (and other modelling software) has a function to convert the triangles to quads after you remeshed it.

**Comment by seongyeong2** [comment]
@Banbury  

Exactly. I was just curious if there’s any consideration for supporting quadrilateral faces through other methods in the future. 
In the case of Blender's remesh with quad, there are quite a few limitations since the mesh needs to be manifold.

**Comment by Banbury** [comment]
'Tris to Quads' in Blender doesn't do a remesh. It just removes the diagonal edge from a quad. So if your mesh is already in quads, 'Tris to Quads' will fix the display, but doesn't change the mesh.

**Comment by seongyeong2** [comment]
@Banbury  Is there another 'tri to quad' feature? I wasn’t aware of it. Can you tell me where it’s located? 😮

![image](https://github.com/user-attachments/assets/39bee490-035d-4de3-8340-a7200183cfd0)

**Comment by Banbury** [comment]
In Edit mode Face/Tris to Quads or press Alt-J.

**Comment by Banbury** [comment]
I would consider myself a gentlemen amateur 😄.
I don't think there is a difference unwrapping tris or quads. Internally a quad is just two triangles. If I have the need to unwrap something programmatically, I use either Blender or Houdini. Houdini is particularly powerful (and free to use), but very difficult to learn.

**Comment by vork** [comment]
Hi,

glb only supports triangles. As most other formats are a bit of a hassle with external texture files (would require zipping) or material parameter definitions, I opted to only support glb for the demo. But internally, it's a trimesh and can be exported to all supported formats with some minor modifications to [run.py](https://github.com/Stability-AI/stable-fast-3d/blob/main/run.py#L118-L124)

In theory, the UV unwrapping can also be altered to handle quads, but then you need pure quad meshes. Mixing quad/tris is a bit more of a hassle.

**Comment by seongyeong2** [comment]
@vork  Thank you for the response. I have one more question, though I’m not sure if it’s okay to ask it here.

After performing quad remesh and unwrap, I noticed that the final mesh's vertices and edges either change in number or value. Is there a way to export the mesh while preserving the topology of the geometry as it was after the remesh process? 
Or perhaps, I’m wondering if there’s something I might have done incorrectly.

**Comment by vork** [comment]
The UV unwrapping adds duplicated vertices at the UV seams. This is also due to a constraint by trimesh, which does not support UV face indices. As far as I know, most graphics libraries or mesh formats also do not support it. So this is an expected and required behavior.

**Comment by seongyeong2** [comment]
@vork  Thank you for your reply. Actually, I met another problem with using remesh. Could you check for this through  below link?
Thank you for you consideration. :) 

https://github.com/vork/PyNanoInstantMeshes/issues/4
