### ISSUE TITLE
Extracting Gaussian Splatting (GS) from Trimesh Objects in Stable Fast 3D

### ISSUE THREAD

**Issue by johnathan199** [Stability-AI/stable-fast-3d#27]
Hello,

I am relatively new to deep learning and generative AI. I'm currently working with Stable Fast 3D and trying to extract Gaussian Splatting (GS) from a Trimesh object, which is the default output format. Is there a way to obtain Gaussian Splatting directly from Stable Fast 3D? I am aiming for an output format similar to what is provided in the [DreamGaussian](https://github.com/dreamgaussian/dreamgaussian) repository.

Thank you for your assistance.

**Comment by vork** [comment]
Gaussian splatting is an entirely different concept, more akin to a volumetric representation. We directly output usable meshes for any traditional game or rendering engine. These should also provide higher rendering speeds. If - for whatever reasons - you need GS you can look at [SuGaR](https://github.com/Anttwo/SuGaR).
