### ISSUE TITLE
How to use it on AWS Sagemaker or AWS in general? 

### ISSUE THREAD

**Issue by NileshArnaiya** [Stability-AI/stable-fast-3d#28]
Hi, would love to test it on our production systems for interior design generator. Is it possible to use with AWS and if yes how do I go about it? Please guide

**Comment by jammm** [comment]
On AWS EC2 instances with NVIDIA GPUs perhaps with Ubuntu OS, I would imagine following the steps in the README.md should be enough.

**Comment by NileshArnaiya** [comment]
Thanks, I'll look into it.
