### ISSUE TITLE
Can't build texture_baker

### ISSUE THREAD

**Issue by Banbury** [Stability-AI/stable-fast-3d#35]
OS: Windows 11
Compiler: Visual Studio 2022
Commit: f0f7005

When installing the requirements, the build process fails, while trying to build texture_baker.
I have attached the [build.log](https://github.com/user-attachments/files/16787524/build.log). It is very long, and doesn't tell me anything.

Pytorch (with cuda), setuptools==69.5.1 and wheel are all installed.

**Comment by vork** [comment]
Can you try building again with the latest push?

**Comment by DmitryFX** [comment]
Same problem.
Win10, Py 3.12, cuda 11.8
Log included.
[texture_baker_fail_log.txt](https://github.com/user-attachments/files/16826316/texture_baker_fail_log.txt)

**Comment by rjg202798772** [comment]
Which is the latest push
