### ISSUE TITLE
cannot import name 'TextureBaker' from 'texture_baker' (unknown location)

### ISSUE THREAD

**Issue by oldtimeleaper** [Stability-AI/stable-fast-3d#42]
got this error when run gradio_app.py in conda env on windows:

Traceback (most recent call last):
  File "D:\AI\stable-fast-3d\run.py", line 10, in <module>
    from sf3d.system import SF3D
  File "D:\AI\stable-fast-3d\sf3d\system.py", line 32, in <module>
    from texture_baker import TextureBaker
ImportError: cannot import name 'TextureBaker' from 'texture_baker' (unknown location)

**Comment by mrtpk** [comment]
Hi @oldtimeleaper , how did you solve this?

**Comment by faxcorp** [comment]
> I think is the problem is texture_baker is not build correctly. For my case , I creat a new conda envirement and set the python version to 3.10.8 and problem solved. FYI @mrtpk

Could you be more specific about the steps required to do that? Im also experiencing this issue but I cant even see 3.10.8 python version in Anaconda

**Comment by mrtpk** [comment]
Hello @faxcorp, I solved this by updating old repo code by doing a 'git pull' and then following install instructions in the readme.

**Comment by mrtpk** [comment]
> I think is the problem is texture_baker is not build correctly. 
> 
> For my case , I creat a new conda envirement and set the python version to 3.10.8 and problem solved.
> 
> FYI @mrtpk 

Thank you for your prompt response. Your comment on texture baker build helped me solve my issue.

I was using an older codebase of sf3d. Updating the code,and reinstalling dependencies solved my issue.
