### ISSUE TITLE
support multiple image inputs

### ISSUE THREAD

**Issue by LingYinTianMeng** [Stability-AI/stable-fast-3d#8]
Can it support multiple image inputs, such as panoramic images of an object, so that parts not visible in a single image, for example, if one image only shows the front of an object, I can provide another image of the back to enhance the quality of the generated 3D model?

**Comment by vork** [comment]
Currently, our main goal is rapid prototyping, where multiple images alongside camera poses of an object are rare. We might revisit that in the future.

So, at this time, it is specifically built for single-image inputs.
