### ISSUE TITLE
module 'pynim' has no attribute 'remesh'

### ISSUE THREAD

**Issue by ericthesolid** [Stability-AI/stable-fast-3d#9]
File "/home/work/stable-fast-3d/sf3d/models/mesh.py", line 149, in quad_remesh
    new_vert, new_faces = pynim.remesh(
AttributeError: module 'pynim' has no attribute 'remesh'

**Comment by vork** [comment]
See #1 - It seems the package didn't build. 

@jammm recently pushed a windows fix to that repo. 
[`https://github.com/Stability-AI/stable-fast-3d/issues/1#issuecomment-2264729746`](https://github.com/Stability-AI/stable-fast-3d/issues/1#issuecomment-2264729746). You can try a reinstall of that package using: `pip install git+https://github.com/vork/PyNanoInstantMeshes.git`
